### ISSUE TITLE
Incomatibility with Piwigo v14

### ISSUE THREAD

**Issue by AndyJAllen** [Piwigo/ContactForm#17]
The contact form doesn't load at all for me after upgrading to piwigo v14.

**Comment by klaoun** [comment]
Hi
Have you a screen and is possible what php

**Comment by AndyJAllen** [comment]
It's completely blank. No content loads. PHP 7.4
![image](https://github.com/Piwigo/ContactForm/assets/19735797/361c0274-fcde-4dd3-aef2-0295de6334c8)

**Comment by klaoun** [comment]
hello
try uninstall delete and install

**Comment by AndyJAllen** [comment]
> hello try uninstall delete and install

That worked. Thanks!
